# Sentiment Analysis Accuracy Review

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../static/data/nlp_sentiment_results.csv")

In [3]:
df.head()

,listing_id,vote_sentiment_positive_count,vote_sentiment_negative_count,vote_sentiment_positive_percent,vote_sentiment_positivity,high_conf_sentiment_positive_count,high_conf_sentiment_negative_count,high_conf_sentiment_positive_percent,high_conf_sentiment_positivity,long_conf_sentiment_positive_count,...,listing_url,name,accommodates,price,property_type,room_type,number_of_reviews,minimum_nights,maximum_nights,Unnamed: 30
0,32396,8.0,NaN,1.000000,1,7.0,1.0,0.875000,1,4.0,...,https://www.airbnb.com/rooms/32396,South Austin Comfort,6,55.0,House,Entire home/apt,9,1,7,NaN
1,69352,227.0,162.0,0.583548,0,320.0,68.0,0.824742,1,267.0,...,https://www.airbnb.com/rooms/69352,Enchanting Zilker Cottage~Downtown,2,159.0,House,Entire home/apt,390,2,45,NaN
2,145210,106.0,76.0,0.582418,0,154.0,28.0,0.846154,1,142.0,...,https://www.airbnb.com/rooms/145210,Maiden Lane Guesthouse,2,129.0,Guesthouse,Entire home/apt,182,3,365,NaN
3,300574,193.0,111.0,0.634868,0,263.0,41.0,0.865132,1,222.0,...,https://www.airbnb.com/rooms/300574,Hip Retro Groovy LOFT South Austin Style,4,124.0,Guesthouse,Entire home/apt,307,2,222,NaN
4,364121,1.0,NaN,1.000000,1,1.0,NaN,1.000000,1,NaN,...,https://www.airbnb.com/rooms/364121,Private romantic getaway 150' above Lake Travis,2,210.0,Bed and breakfast,Hotel room,1,2,7,NaN

In [4]:
cols = ["listing_id", "vote_sentiment_positivity", "high_conf_sentiment_positivity", 
        "long_conf_sentiment_positivity", "classified_sentiment_positivity",
        "review_scores_rating"
       ]
df = df[cols]
df.head()

,listing_id,vote_sentiment_positivity,high_conf_sentiment_positivity,long_conf_sentiment_positivity,classified_sentiment_positivity,review_scores_rating
0,32396,1,1,0,1,97.0
1,69352,0,1,0,1,95.0
2,145210,0,1,1,1,98.0
3,300574,0,1,1,1,97.0
4,364121,1,1,0,1,100.0

In [5]:
def true_positivity(row):
    if row["review_scores_rating"] > 80:
        return 1
    else:
        return 0

In [6]:
df["true_positivity"] = df.apply(true_positivity, axis=1)
df.head()

,listing_id,vote_sentiment_positivity,high_conf_sentiment_positivity,long_conf_sentiment_positivity,classified_sentiment_positivity,review_scores_rating,true_positivity
0,32396,1,1,0,1,97.0,1
1,69352,0,1,0,1,95.0,1
2,145210,0,1,1,1,98.0,1
3,300574,0,1,1,1,97.0,1
4,364121,1,1,0,1,100.0,1

In [7]:
sum(df["vote_sentiment_positivity"] == df["true_positivity"])/df.shape[0]

0.1630509248686915

In [8]:
sum(df["high_conf_sentiment_positivity"] == df["true_positivity"])/df.shape[0]

0.8186800639415391

In [9]:
sum(df["long_conf_sentiment_positivity"] == df["true_positivity"])/df.shape[0]

0.4709979447362411

In [10]:
sum(df["classified_sentiment_positivity"] == df["true_positivity"])/df.shape[0]

0.654144781913679

According to these accuracy scores, the high confidence measure is the best of them all (although not perfect) and the vote measure is trash.